### ISSUE TITLE
Importing Icon with SvelteKit

### ISSUE THREAD

**Issue by Gibbu** [JustinVoitel/svelte-hero-icons#5]
When importing the icon and the variants it will result in a `SyntaxError: Cannot use import statement outside a module`

![image](https://user-images.githubusercontent.com/20338746/112726553-2d100380-8f72-11eb-8ac9-62a4275540ee.png)

I've added the `optimizeDeps` into the `svelte.config.cjs`:
```js
kit: {
  adapter: adapter(),
  target: 'body',
  vite: {
    optimizeDeps: {
      include: ['svelte-hero-icons']
    },
    ssr: {
      noExternal: Object.keys(pkg.dependencies || {})
    }
  }
}
```

Code I'm using:
```html
<!-- $layout.svelte -->
<script>
  import Icon, {Home} from 'svelte-hero-icons';
</script>

<a href="/">
  <Icon src={Home} size="24" />
</a>
```

`package.json` if that matters:
![image](https://user-images.githubusercontent.com/20338746/112726946-1074cb00-8f74-11eb-9aa8-5e217ef952a1.png)

**Comment by thormuller** [comment]
I have the same issue. Did you ever resolve this @Gibbu?

**Comment by JustinVoitel** [comment]
@Gibbu @thormuller sorry for the late answer but moving the package from `devDependencies` to `dependencies` fixed the error for me

**Comment by Gibbu** [comment]
That indeed fixed it.

**Comment by thormuller** [comment]
Sadly, I'm getting a slightly different error with the latest version (2.1.2):

```
Error when evaluating SSR module /node_modules/svelte-hero-icons/dist/Icon.svelte:
SyntaxError: Unexpected token '?'
```

Any thoughts on if this is a package issue or a config issue on my end? My config is exactly as Gibbu describes above, with the inclusion of of the package to `dependencies`.

**Comment by JustinVoitel** [comment]
Seems like a config issue with resolving the ternary operator. I never encountered this issue before so I'd love to see a minimal reproduction of your project so I  am try to break it down

**Comment by thormuller** [comment]
This seems like an SSR issue since it works just fine when I add the import and component to index.svelte and the page hot reloads. 

**svelte.config.cjs**
![image](https://user-images.githubusercontent.com/395315/114274828-78e49300-99dd-11eb-8147-3581bc37deef.png)

**package.json**
![image](https://user-images.githubusercontent.com/395315/114274773-45a20400-99dd-11eb-88ef-b0f39ddbe367.png)

**index.svelte**
![image](https://user-images.githubusercontent.com/395315/114275252-112f4780-99df-11eb-8cb3-911752ac8ef4.png)

**Comment by thormuller** [comment]
FYI, I removed the ternary operators and it works fine now. Obviously there's something else going on here related to Vite, SSR and the ternary, but I don't have time to dig in further.

**Comment by JustinVoitel** [comment]
@thormuller have you replaced it with if statements or removed the width logic completely ?

I'll try to push a version with 'if' later if I find some time ;)

**Comment by JustinVoitel** [comment]
@thormuller I just published version 2.2.0-beta.0 with a fix for your issue. Please try it out so I can publish 2.2.0
But I have still no idea why this is happening with your setup as it worked out perfectly for me before the fix :/

**Comment by thormuller** [comment]
Ah, thanks @JustinVoitel! I'll install and let you know how it goes. Hopefully this is a fix that helps others as well. Your package is a wonderful time saver so kudos for all your work!

**Comment by thormuller** [comment]
Sorry for my slow response, @JustinVoitel. The bad news is that your beta release did not fix the issue–the problematic syntax was in Nullish coalescing operator.

The good news is that after digging in a bit, I realized the underlying issue is that my local Node version was 12.x, which doesn't support the Nullish coalescing operator. Upgrading to 14.x fixed the issue. Obvious in retrospect. So perhaps the pragmatic change for you (to avoid more such issues taking up your time) is to explicitly mention the minimum Node version in the documentation :) 

Again, thanks for your work.
